# Inserts a blank line between shell prompts
add_newline = false
command_timeout = 1000
palette = "catppuccin_frappe"

format = """
 $directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$c\
$cmake\
$python\
$nix_shell\
$line_break \
$cmd_duration\
$jobs\
$status\
$character"""

# ${custom.nix_shell}\

[directory]
style = "bold sapphire"

[git_branch]
style = "bold blue"

[git_status]
style = 'bold maroon'

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = '[\$](bold sapphire)' # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[nix_shell]
symbol = '❄️ '
style = 'bold teal'

[python]
symbol = ' '
style = 'bold green'

[c]
style = 'bold green'

[cmake]
style = 'bold green'

# Custom module that prints the packages installed via nix-shell
[custom.nix_shell]
when='[ -n "$buildInputs" ]'
command="~/.local/bin/nix-shell_buildInput.sh"
style="bold blue"
format='via [❄️\($output\)]($style)'

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
