#!/usr/bin/env bash

REPO_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
FILES=$(cd "$REPO_PATH" && fzf -f '')
RED='\033[0;31m'
GREEN='\033[0;32m'
RESET='\033[0m'

for file in $FILES
do
    if [[ -f "$HOME/$file" ]]
    then
        cp "${HOME}/$file" "${REPO_PATH}/$file"
        echo -e "${GREEN}Successfully updated $file with $HOME/$file${RESET}"
    else
        echo -e "${RED}$file not updated"
    fi
done
