# Inserts a blank line between shell prompts
add_newline = false

format = """
 $directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$python\
$nix_shell\
$line_break \
$cmd_duration\
$jobs\
$status\
$container\
$character"""

# ${custom.nix_shell}\

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[nix_shell]
symbol='❄️ '

# Custom module that prints the packages installed via nix-shell
[custom.nix_shell]
when='[ -n "$buildInputs" ]'
command="~/.local/bin/nix-shell_buildInput.sh"
style="bold blue"
format='via [❄️\($output\)]($style)'
